<?php

namespace AppBundle\Repository;

/**
 * KontaktniOsobaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KontaktniOsobaRepository extends \Doctrine\ORM\EntityRepository
{
}
