<?php

namespace AppBundle\Repository;

/**
 * LogNotifikaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogNotifikaceRepository extends \Doctrine\ORM\EntityRepository
{
}
