<?php

namespace AppBundle\Repository;

/**
 * LogObsluhyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogObsluhyRepository extends \Doctrine\ORM\EntityRepository
{
}
