<?php

namespace AppBundle\Repository;

/**
 * PokusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokusRepository extends \Doctrine\ORM\EntityRepository
{
}
