# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

        AppBundle\Entity\Pracovnik:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$OCMN2VYeDWnbgr3xpXrkL.X7Yj5xx5nq3zC5OD2ufQeZoK0GQxuBm
                        roles: 'ROLE_ADMIN'
                    pracovnik:
                        password: $2y$13$OCMN2VYeDWnbgr3xpXrkL.X7Yj5xx5nq3zC5OD2ufQeZoK0GQxuBm
                        roles: 'ROLE_PRACOVNIK'
        user_db:
            entity: { class: AppBundle:Pracovnik, property: email }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: login_form[_username]
                password_parameter: login_form[_password]
            logout:
                path: /logout
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_VEDOUCI }
    # require ROLE_ADMIN for /admin*

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false

