# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt

        AppBundle\Entity\Pracovnik:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$OCMN2VYeDWnbgr3xpXrkL.X7Yj5xx5nq3zC5OD2ufQeZoK0GQxuBm
                        roles: 'ROLE_ADMIN'
                    pracovnik:
                        password: $2y$13$OCMN2VYeDWnbgr3xpXrkL.X7Yj5xx5nq3zC5OD2ufQeZoK0GQxuBm
                        roles: 'ROLE_PRACOVNIK'
                    dashboard:
                        password: $2y$13$OCMN2VYeDWnbgr3xpXrkL.X7Yj5xx5nq3zC5OD2ufQeZoK0GQxuBm
                        roles: 'ROLE_DASHBOARD'
        user_db:
            entity: { class: AppBundle:Pracovnik }

        api_provider:
            entity:
                class: AppBundle:Pracovnik
                property: token


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/*
            provider: api_provider
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator
            anonymous: ~

        main:
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: login_form[_username]
                password_parameter: login_form[_password]
                default_target_path: redirect
                always_use_default_target_path: true
            logout:
                path: /logout
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/redirect, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard2, roles: [ROLE_DASHBOARD, ROLE_ADMIN, ROLE_VEDOUCI] }
        - { path: ^/api/, roles: ROLE_API }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_VEDOUCI] }

    # require ROLE_ADMIN for /admin*

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false

